# -*- makefile -*-
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/h2hI2.pcap h2hR1.pcap
TESTNAME=h2hI2
ENDNAME=h2h
CONNNAME=mytunnel

pcapupdate:
	cp ../lp37-h2hR1/OUTPUT/h2hR1.pcap h2hR1.pcap




