# -*- makefile -*-
CONNNAME=home
PCAPOUTPUT=parentI2.pcap
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${PCAPOUTPUT} parentR1dave.pcap
ENDNAME=davecert

TESTNAME=davecertI2

pcapupdate:
	@true




