# -*- makefile -*-
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/nat_traversal.o
EXTRALIBS+=${LIBPLUTO}

CONNNAME=t4901
ENDNAME=h2h-ikev1
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentN1.pcap OUTPUT/parentM2.pcap
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=parentM2

pcapupdate:
	cp ../lp73-parentN1/OUTPUT/parentN1.pcap parentN1.pcap


