# -*- makefile -*-
CONNNAME=rw
ENDNAME=moon
INPUTPCAPS=v1certM1.pcap v1certM2.pcap v1certM3.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap ${INPUTPCAPS}
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=v1certN3

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/nat_traversal.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ac.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/signatures.o

EXTRALIBS+=${LIBPLUTO}

pcapupdate:
	cp ../../libpluto/lp82-v1certM1/OUTPUT/v1certM1.pcap v1certM1.pcap
	cp ../../libpluto/lp84-v1certM2/OUTPUT/v1certM2.pcap v1certM2.pcap
	cp ../../libpluto/lp86-v1certM3/OUTPUT/v1certM3.pcap v1certM3.pcap
